"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <FULL NAME> and <FULL NAME>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:
UT EID 2:
"""


def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    rails = [[] for _ in range(key)]
    current = 0
    direction = 1
    for char in string:  # Processes all characters including spaces
        rails[current].append(char)
        current += direction
        if current == 0 or current == key - 1:
            direction *= -1
    return ''.join([''.join(rail) for rail in rails])


def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    pattern = []
    current = 0
    direction = 1
    for _ in range(len(string)):
        pattern.append(current)
        current += direction
        if current == 0 or current == key - 1:
            direction *= -1
    rails = []
    for rail_num in range(key):
        rails.append([char for i, char in enumerate(string) if pattern[i] == rail_num])
    result = []
    current = 0
    direction = 1
    railind = [0] * key
    for _ in range(len(string)):
        result.append(rails[current][railind[current]])
        railind[current] += 1
        current += direction
        if current == 0 or current == key - 1:
            direction *= -1
    return ''.join(result)


def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    result = []
    for char in string.lower():
        if 'a' <= char <= 'z':
            result.append(char)
    return ''.join(result)


def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    pval = ord(p) - ord('a')
    sval = ord(s) - ord('a')
    encode = (pval + sval) % 26
    return chr(encode + ord('a'))


def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    pval = ord(p) - ord('a')
    sval = ord(s) - ord('a')
    decode = (sval - pval) % 26
    return chr(decode + ord('a'))


def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    filterr = filter_string(string)
    phrase = filter_string(phrase)
    if not phrase:
        return filterr
    result = []
    leng = len(phrase)
    for i, char in enumerate(filterr):
        pchar = phrase[i % leng]
        result.append(encode_character(pchar, char))
    return ''.join(result)


def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    filterr = filter_string(string)
    phrase = filter_string(phrase)
    if not phrase:
        return filterr
    result = []
    phrase_len = len(phrase)
    for i, char in enumerate(filterr):
        pchar = phrase[i % phrase_len]
        result.append(decode_character(pchar, char))
    return ''.join(result)


def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)
    plain = input()
    # read the key from stdin (terminal/input)
    key = int(input())
    # encrypt and print the encoded text using rail fence cipher
    print(rail_fence_encode(plain, key))
    # read encoded text from stdin (terminal/input)
    encode = input()
    # read the key from stdin (terminal/input)
    key = int(input())
    # decrypt and print the plain text using rail fence cipher
    print(rail_fence_decode(encode, key))
    # read the plain text from stdin (terminal/input)
    plain = input()
    # read the pass phrase from stdin (terminal/input)
    phrase = input().strip()
    # encrypt and print the encoded text using Vigenere cipher
    print(vigenere_encode(plain, phrase))
    # read the encoded text from stdin (terminal/input)
    encode = input()
    # read the pass phrase from stdin (terminal/input)
    phrase = input().strip()
    # decrypt and print the plain text using Vigenere cipher
    print(vigenere_decode(encode, phrase))

# Do NOT modify the following code.
if __name__ == "__main__":
    main()
